"""added request description

Revision ID: 08c4170b9226
Revises: b068e92d5b01
Create Date: 2021-07-13 20:25:27.361925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08c4170b9226'
down_revision = 'b068e92d5b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_description', sa.String(length=200), nullable=False))
        batch_op.drop_column('request_type_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('request_description')

    # ### end Alembic commands ###
