"""added FK in userrequests table

Revision ID: 2591c269874e
Revises: 3a7c4803d18c
Create Date: 2021-07-13 20:42:15.697608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2591c269874e'
down_revision = '3a7c4803d18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcms', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
