"""added FK in userrequests table

Revision ID: 3a7c4803d18c
Revises: ce1c401771b7
Create Date: 2021-07-13 20:35:24.713605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7c4803d18c'
down_revision = 'ce1c401771b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'requestcategory', ['request_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###
