"""added iamge ht and width

Revision ID: 4133f4d06bff
Revises: be94521ef79c
Create Date: 2021-07-19 17:57:57.087137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4133f4d06bff'
down_revision = 'be94521ef79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('width', sa.String(length=200), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic_height', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_width', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_width')
        batch_op.drop_column('profile_pic_height')

    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.drop_column('width')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
