"""added fcm table

Revision ID: b8eb264eed1e
Revises: c920060053c7
Create Date: 2021-07-13 19:29:09.449329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8eb264eed1e'
down_revision = 'c920060053c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcms', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['device_id'])
        batch_op.create_unique_constraint(None, ['fcm_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fcms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
