"""added FK in userrequests table

Revision ID: be94521ef79c
Revises: e37e005a7e97
Create Date: 2021-07-14 18:53:00.396511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be94521ef79c'
down_revision = 'e37e005a7e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(length=200), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrequests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
